FROM node:18.13.0-alpine

ENV NODE_ENV production

# Enable chokidar polling so hot-reload mechanism can work on docker or network volumes
ENV CHOKIDAR_USEPOLLING true

WORKDIR /usr/src/app

RUN apk --no-cache upgrade

COPY package.json package-lock.json /usr/src/app/
RUN npm install

EXPOSE 8080 9876

CMD [ "node", "lib", "index.js" ]

COPY . /usr/src/app
